/* Auto-generated by Tools/build/generate_token.py */

/* Token types */
#ifndef Py_INTERNAL_TOKEN_H
#define Py_INTERNAL_TOKEN_H
#ifdef __cplusplus
extern "C" {
#endif

#ifndef Py_BUILD_CORE
#  error "this header requires Py_BUILD_CORE define"
#endif

#undef TILDE   /* Prevent clash of our definition with system macro. Ex AIX, ioctl.h */

#define ENDMARKER       0
#define NAME            1
#define NUMBER          2
#define STRING          3
#define NEWLINE         4
#define INDENT          5
#define DEDENT          6
#define LPAR            7
#define RPAR            8
#define LSQB            9
#define RSQB            10
#define COLON           11
#define COMMA           12
#define SEMI            13
#define PLUS            14
#define MINUS           15
#define STAR            16
#define SLASH           17
#define VBAR            18
#define AMPER           19
#define LESS            20
#define GREATER         21
#define EQUAL           22
#define DOT             23
#define PERCENT         24
#define LBRACE          25
#define RBRACE          26
#define EQEQUAL         27
#define NOTEQUAL        28
#define LESSEQUAL       29
#define GREATEREQUAL    30
#define ALMOSTEQUAL     31
#define TILDE           32
#define CIRCUMFLEX      33
#define LEFTSHIFT       34
#define RIGHTSHIFT      35
#define DOUBLESTAR      36
#define PLUSEQUAL       37
#define MINEQUAL        38
#define STAREQUAL       39
#define SLASHEQUAL      40
#define PERCENTEQUAL    41
#define AMPEREQUAL      42
#define VBAREQUAL       43
#define CIRCUMFLEXEQUAL 44
#define LEFTSHIFTEQUAL  45
#define RIGHTSHIFTEQUAL 46
#define DOUBLESTAREQUAL 47
#define DOUBLESLASH     48
#define DOUBLESLASHEQUAL 49
#define AT              50
#define ATEQUAL         51
#define RARROW          52
#define ELLIPSIS        53
#define COLONEQUAL      54
#define EXCLAMATION     55
#define OP              56
#define AWAIT           57
#define ASYNC           58
#define TYPE_IGNORE     59
#define TYPE_COMMENT    60
#define SOFT_KEYWORD    61
#define FSTRING_START   62
#define FSTRING_MIDDLE  63
#define FSTRING_END     64
#define ERRORTOKEN      65
#define N_TOKENS        69
#define NT_OFFSET       256

/* Special definitions for cooperation with parser */

#define ISTERMINAL(x)           ((x) < NT_OFFSET)
#define ISNONTERMINAL(x)        ((x) >= NT_OFFSET)
#define ISEOF(x)                ((x) == ENDMARKER)
#define ISWHITESPACE(x)         ((x) == ENDMARKER || \
                                 (x) == NEWLINE   || \
                                 (x) == INDENT    || \
                                 (x) == DEDENT)
#define ISSTRINGLIT(x)          ((x) == STRING           || \
                                 (x) == FSTRING_MIDDLE)


// Symbols exported for test_peg_generator
PyAPI_DATA(const char * const) _PyParser_TokenNames[]; /* Token names */
PyAPI_FUNC(int) _PyToken_OneChar(int);
PyAPI_FUNC(int) _PyToken_TwoChars(int, int);
PyAPI_FUNC(int) _PyToken_ThreeChars(int, int, int);

#ifdef __cplusplus
}
#endif
#endif  // !Py_INTERNAL_TOKEN_H
